[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read", path = "./out/"},
    { access = "read-write", path = "./script/output/"}
]
